project:
  type: website
  output-dir: docs

website:
  title: "crickleaze.cc"
  favicon: "crickheart.png"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

include-in-header:
  text: <link rel="shortcut icon" href="crickheart.png" />

