name: Publish Website

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: ['main']

jobs:
  quarto:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Ensure this action is compatible with Node.js 20

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.0'  # Adjust as necessary

      - name: Install R dependencies
        run: |
          install.packages('remotes')
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
        
      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup Pages
        uses: actions/configure-pages@v1 # Ensure this action is compatible with Node.js 20

      - name: Render Website
        run: quarto render

      - name: Create CNAME file
        run: echo 'www.crickleaze.cc' > _site/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '_site'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1 # Updated to a hypothetical version that uses Node.js 20

      - name: Set Environment URL
        run: echo "url=${{ steps.deployment.outputs.page_url }}" >> $GITHUB_ENV
